import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavBar from '../components/Navbar/Navbar'
import Login from '../components/Login/Login'
import Viewport from '../components/Viewport/Viewport'
import dynamic from 'next/dynamic'
const DynamicImport = dynamic(() => import('../components/Particles.jsx'),{
  ssr: false,
})
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
  
      </Head>

      <main className={styles.main}>    
        <DynamicImport/>
        <div id="particles-js" style={{height: "100vw", width: "100vw", position: "fixed"}}></div>  
        <NavBar/>
        <Viewport>       
          <Login/>
        </Viewport>

      </main>

    </div>
  )
}
